repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
      - id: trailing-whitespace
        types: [file, text]
      - id: end-of-file-fixer
        types: [python]
      - id: mixed-line-ending
        types: [python]
        args: ["--fix=lf"]

  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black
        types: [python]

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
